travis:
  secure:
    BINSTAR_TOKEN: gKp/ffT/yrTboSEnRrp7wlUuw/fgIj9nl7Lvqox8z8ykiqz4rm8Rh4d2dD7/wqCDChcrGOe/dEvWgVbATHfF80GzJTep/ZAsDjZRI1NR+GjvNnl/31s2KkYt/pSC85r5YyfRqIjygoMZKjqr9LruIdbrqsTKEqY3X2WGZLYgPBfX+gjZbAs9RZoesD8RlgErhKxqjkDkZJQWLzBfLKBQW2nJ9l5jGd1zKmNCxgn/pJ+UUlNkvoSzu1ZbOSEh5NwkIGYQVYCAHCwyUUrXlL7gMBRQALppyHf1+inMCEu8h9BzZgmefgnz+EuoFQVg2XWoPoW55v/VodFzYVPzyJWoIuGho02dZhVIgxZzaSkvF5Hn5je2l1AQw0vfvQ4lenDOetQyNH7NXwHb8XSpL1/BqNniRbUYr+7HveY1RR2s02JdFazP1WZrvv/8ljj+0Up0eHbYgGPk2fLhZ4WMAXWevwKo8moExjQ6eTjPMssyBl9+KHGdOHLGKFQUDQdxehoLVtWh+ctDBSMOXnAsrd+ZM+UvU8qckiXVrukac82OcUcqhPOG5BYtod73A/J/WApQQsH6xj4k45mijojXIgexyWLsUeu/wFBLaTplAG7r+KctjFqs+ZP6XeZDJ+PmV6cIkOQ7j1UUTiQEaiioy7aUtq2fKh38W8F7J/20c/49Zmg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
