travis:
  secure:
    BINSTAR_TOKEN: f5fl//2aj+97rSpFdxAAmEtMPBjkSFls4He5lNEnEW5obdNUEDUndoc53RcKk0AkDYUrFQkn6IP9iX7Fnkmfxr1/0gtVL27mqk+1r3MgNzaOgY+3HC9WbuZhhKom8qaQ7GyInEgumU9quWgmS1nIKBbt1/EiSZTmbXB5Onjo8ix1Vq1EjWfghQbFWCrojO5hDn1unLd/zB3B5zD8aNH+/9o2joxmyWC9uAzadTHTCPr1AGRJ2xaDJ9VGXpbJsrmizHqPUhr3FUvpd7DaMyCA1GVHm5gsxdEbn+dLO1YzZhRBtTF0KhDp9F1Xoq/zlOizC1Ecc6CwIwldMAfKVFiq+gY+0VwEAT+O30EfEviK13hvXiWyfFvZzS+7ft6xhrwXDYCPSYOW9UOEEbTn/oYsrQ+el+MF78HgWXyD4UJd9hwYt051SaJ97Yw0IbtKJle19wh/yrDTrryoq9CwBYI1/HuWj0o5a2LURpkr8lPB7MkvrNYL5jGceJyrNJXrD8gvl4zuQsuo2suZyiwIZ35gDH0k8f7VJvx0a4WYLkFvaKOpNyX4r5WtXlYxcOgTKqxR+/7L9NGrRRa24EuqZzYx8lMftWyUIF1pl3AZuenal83C6MCrfKpUrW7gGx66Y9s6WXVXoB318cBFt5X/q4okin0lePRUtoitSqW7lOr1Sj4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
