travis:
  secure:
    BINSTAR_TOKEN: D/Msg3pqueW2VPrWw8iQ3ONcUoINomcM2jU2xSWqBAWxbSF7U0RtdXsC91wM1vXNfiHvepjhKZTg51LSG640VjAqSrOqth+h6dr9YJnM84u8gZbqfgi0ukFfmT9IQj1jsCyRfWPS1ogNxkibWn4Z1qp8VsTTGs+zEwMOIssiDbKNn5aYTRLO49kS1V6aCsVuGW3i7IBAjCgpXpi7+ikEss5Ba5sidvsr9wvj0s2aCBOSxxdtwDq6f9FRMoQ0vkjSGUGI5QC5FM4T3+7drb4kX1j7Pq+2Hou6q9NEEOUEsKduYivQGe4Xqabe7K96wEXVycRzXdmybOWj09odTb5Yk9BLMisv4x3okUgzKRLF2/bh31hQOuRsH+ckMmNSvB2lA5ruuDVsv9yUiQ33K5CZbdoHXFGHW3GORJkhd/uEsJnXwsEx8E2Vnd/wOUyilb/X9qZO/YEQUc6ThaEO+pc+RXviNSY6YHb6ds/8jVCwK/7OOwlh3V5+fSQomFO/0ZTa6pXuONKoSJ/fYPD0D7o8MMqzRuj5UTS7w3LUvSmI2YnfuVMLv1FV/BPPb82iJHpWaf7fmDh7fYanhd7eXdaU9UmfvvdrC2Fg40/0cavpjXuNAh14FnKZHNjc3lMxQj5QtIgxnT7yD50kdoCbSL5RyVAkQXf9qc16jtZbPmSgois=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
